# Generated by Django 4.2.3 on 2023-07-24 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
