# Generated by Django 4.2.3 on 2023-07-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyApp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='user',
        ),
        migrations.AddField(
            model_name='spotifytoken',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='spotifytoken',
            name='scope',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='expires_in',
            field=models.IntegerField(),
        ),
    ]
