# Generated by Django 4.2.3 on 2023-07-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyApp', '0004_remove_spotifytoken_user_spotifytoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='user_id',
            field=models.CharField(default='defaultvalue', max_length=50, unique=True),
        ),
    ]
